### ISSUE TITLE
Dum Drums mapping always goes back to default

### ISSUE THREAD

**Issue by rellimneb** [JoepVanlier/JSFX#106]
I've altered the mapping in the Dum Drums plugin.  But as soon as I hit play the mapping reverts to default...
I can save a plugin preset and the mapping gets saved with it, but it still gets reset when hiting play.
If i change the mapping or recall my preset while it is playing then it works, but only up until the point when i hit stop and then play again.

**Comment by JoepVanlier** [comment]
Hm, on the latest version I have not been able to reproduce the issue locally.

Are you on the latest version? There was a bug in 0.13 that constantly reset the note mapping, but it should have been fixed in 0.14 (https://github.com/JoepVanlier/JSFX/commit/ffce823ab824a20d407ec5401ac38d47046cfa79). You can verify this by hitting the edit button on the top right. Editing the JSFX will show you the current version at the top somewhere. Currently, the latest version is 0.15.

**Comment by rellimneb** [comment]
ah that was it.  sorry, i thought i was already in the latest version.  thanks

**Comment by JoepVanlier** [comment]
Ah cool! No worries!
