### ISSUE TITLE
Idea: Offline Spectrum Analiser

### ISSUE THREAD

**Issue by dcocharro** [JoepVanlier/JSFX#30]
Something that I used very often in cubase for items analysis was the offline **statistics** and the **spectrum analyser** .
It's very useful, the user just selects an item, runs the analysis and a window opens with the result.
Looks something like the attached picture.

I have been looking for some reaper extension that would perform a similar task, without the playback necessity (in order words, not real-time). Here I opened a thread: [https://forum.cockos.com/showthread.php?t=265120](https://forum.cockos.com/showthread.php?t=265120)

![Screen Shot 2022-04-06 at 16 19 02](https://user-images.githubusercontent.com/405771/162009412-3dd9adc7-5931-45f0-94fc-491bd83f41cd.png)

Thank you

**Comment by JoepVanlier** [comment]
Probably not that difficult to do, but maybe better suited in a separate repo, as I would probably approach this with Lua rather than JSFX (which are more intended for real time DSP).

How much do you know about the tool? Would be good to have some information on what would be needed. What method is it using to obtain the power spectrum? Is it just an FFT with a rectangular window or is it doing something more advanced?

**Comment by JoepVanlier** [comment]
Closed for inactivity. Please feel to reopen if this is still wanted.
