### ISSUE TITLE
Memory usage is too high when using multiple instances of Saikes spectrum analyser (beta version)

### ISSUE THREAD

**Issue by jc-SpaceXp** [JoepVanlier/JSFX#41]
## Basic Test
   - 1 track (no audio/media items)
     - non-master track
   - Only has 1 plugin
     - Saike spectrum analyser
     - or LSP spectrum plugin
   - Note: My system has 8 Gb RAM (and looking at memory usage from htop command)
### No-plugins
    1.87% Mem usuage
### LSP Spectrum (x1 Mono)
    2.60% Mem usuage
 ### Saike spectrum
    3.06%

### Summary
So memory usage of the spectrum analyser isn't too high. However, when loading multiple tracks with the plugin the memory usage gets excessive. Unsure if the issue is also present in the non-beta version.

## Other Tests
- Just a colour coded project with a spectrum analyser on most channels
### Project Template (Non-Reapack)
    - 2-3% w/o Saike spectrum analyser (per track)
    - 3-4% w/ Saike spectrum analyser (per-track)
    - 9% overall (8 tracks with spectrum including master)
### Project Template (Reapack version with Saike spectrum)
    - 39% overall (8 tracks w/ spectrum including multichannel spec setup manually)

## Other things I noticed
- Current track I'm working on uses 62% of my memory (Reaper has always been kind to my machine regarding memory usage so was surprised to see it so high)
- Each time I remove the spectrum analyser memory usage drops by  3-4% (on bypassed FX and active FX tracks)
- Drops down to around 12% when spectrum analyser is removed from the all of the tracks (15 tracks in total, either bypassed FX or active)
- Drops to 12% usage when replacing Saike spectrum with JSFX cockos version, the LSP spectrum or deleting the plugin and not replacing it
- Drops to around 17-18% when using settings similar to the JSFX version (FFT of 8192 and floor of -90dB)
- Also disabled sonogram to see if that would help and it didn't

**Comment by JoepVanlier** [comment]
Thanks for bringing this to my attention.

While I don't think the multi-spectral one will ever use as little as the native one (due to the extra features like being able to store reference snapshots and other stuff), I have indeed been quite aggressive and sloppy in allocating memory for the plugin using lots of padding for 65536 block alignment and allocating the memory all at once for all 16 channels even when a subset is used. I've been doing some work in reducing this. 

Since the code for this plugin is quite a mess (it started out as a quick and dirty hack to get a few extra features in and just grew), I had to do fairly invasive changes in how things are handled. While I did test my changes at least somewhat, this makes it difficult to guarantee that there were no bad side effects of the overhaul of how memory is handled, so I will be using the more memory efficient spectral analyzer myself for a while before merging it back to master. But if you to wish help test it and find bugs / quirks, I'd be much obliged.

You can find the new version on the following branch:

https://github.com/JoepVanlier/JSFX/tree/less_mem_spectral

The files you would need to overwrite are the JSFX itself: https://raw.githubusercontent.com/JoepVanlier/JSFX/less_mem_spectral/SpectrumAnalyzer/SaikeMultiSpectralAnalyzer.jsfx

But also LoadSpectrum (it was also always setting up 16 tracks): https://raw.githubusercontent.com/JoepVanlier/JSFX/less_mem_spectral/SpectrumAnalyzer/LoadSpectrum.lua

Please let me know if this at least reduces the memory use on your system somewhat.

**Comment by JoepVanlier** [comment]
The PR was [merged](https://github.com/JoepVanlier/JSFX/pull/42) and it's in a release now. Hopefully this mostly resolves the issue for you.
