### ISSUE TITLE
Filther FIR/Oversampling introduces unwanted delay

### ISSUE THREAD

**Issue by NlGHT** [JoepVanlier/JSFX#88]
The plugins are fantastic work!  Thankyou so much.

Filther has an issue currently where oversampling or using FIR mode makes the track delayed and out of sync with everything else.  I reckon it's likely because it doesn't register any plugin delay compensation.  This is visible in the performance meter.  PDC remains at 0 no matter what you do.  This causes everything to be delayed and sadly makes the feature almost unusable.

![FiltherPDCIssue](https://github.com/JoepVanlier/JSFX/assets/36537208/9e70d9c3-d730-4183-8036-6600b4ea2b09)

Here is shown the delay showing with 8x oversampling + FIR when frozen:

![FiltherPDCIssue2](https://github.com/JoepVanlier/JSFX/assets/36537208/fd2c4d4e-ef3e-4aec-8833-1126d451cae1)

**Comment by JoepVanlier** [comment]
Great catch! Thanks for reporting the bug!

I'm not entirely sure why it didn't show _any_ PDC, because it should have shown at least some.

What I did find was that I was actually not compensating the PDC induced by the DC blocker (which is a sizeable amount). Hopefully the patch (version `3.14`) that I just pushed fixes that particular problem and doesn't cause it to delay like this again. Could you give that one a shot?

If that doesn't fix it, I might need to see the preset, if you don't mind sharing it.

While working on this, I also noticed that `Filther` could do with some better quality FIRs for oversampling in the future, so maybe I will have a peek at providing a higher quality alternative at some point too. The sincs work but since they're relatively short FIRs, they roll off a bit more HF content than I would like.

**Comment by NlGHT** [comment]
Yes!  Thankyou so much for fixing that.  It's working like a charm!  Great stuff, super glad you could fix it.  Was a bit worried when I tried to have a go and saw the 17k line count!  Intimidating but impressive stuff.

In terms of the FIR quality i'm not sure what is possible, but the difference is noticeable already and it definitely helps sometimes.  I would be always be up for higher quality though.  I have actually now that you mention it, noticed a slight roll off.  This I just attributed to a decrease in artifacts, but yes you are right.

**Comment by JoepVanlier** [comment]
Awesome! I'm glad it resolved the issue you were having.

I will look into possibly offering a higher quality FIR mode in the future, but for now I will close this issue, since the most acute problem seems solved.

Thanks again for the bug report!
